[book]
title = "開き戸自動化プロジェクトのドキュメント"
description = "開き戸自動化プロジェクトのドキュメントリポジトリです。"
authors = ["Rekonstruu-Auxtomatan-Pordonチーム"]
language = "ja"
multilingual = false
src = "src"
[build]
build-dir = "docs"
create-missing = false
[output.html]
mathjax-support = true
preferred-dark-theme = "navy"
copy-js = true
line-numbers = true
runnable = false

[output.html.playground]
editable = true
copy-js = true
line-numbers = true
runnable = false

[output.html.print]
enable = true
copy-js = true
line-numbers = true
runnable = false
